spring.application.name=to-do-project

jwt.public.pem=classpath:keys/public.pem
jwt.private.pem=classpath:keys/private.pem

# Enables the DATA.SQL for DATABASE
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/mydbtodo1
spring.datasource.username=root
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
